import 'package:flutter/widgets.dart';

import 'app_scope.dart';
import 'firmware_text_adapter.dart';

class FarmerLanguage {
  const FarmerLanguage._();

  static bool _ta(BuildContext context) =>
      AppScope.of(context).settings.value.languageCode == 'ta';

  static bool isTamil(BuildContext context) => _ta(context);

  static String label(BuildContext context, String key) {
    final map = _ta(context) ? _taLabels : _enLabels;
    return map[key] ?? _enLabels[key] ?? key;
  }

  static String firmware(BuildContext context, String? raw,
      {String fallback = ''}) {
    if (raw == null || raw.trim().isEmpty) return fallback;
    final clean = raw.trim();
    final key = clean
        .toUpperCase()
        .replaceAll(RegExp(r'[^A-Z0-9]+'), '_')
        .replaceAll(RegExp(r'^_+|_+$'), '');
    final map = _ta(context) ? _taFirmware : _enFirmware;
    return map[key] ?? FirmwareTextAdapter.text(context, clean);
  }

  static String confidence(BuildContext context, double? value) {
    if (value == null) return label(context, 'not_available');
    if (value >= 80) return label(context, 'high');
    if (value >= 55) return label(context, 'medium');
    return label(context, 'low');
  }

  static const _enLabels = <String, String>{
    'analysis': 'Analysis',
    'sensors': 'Sensors',
    'history': 'History',
    'camera': 'Camera',
    'settings': 'Settings',
    'simulation': 'Simulation',
    'simulated': 'SIMULATED',
    'simulation_description': 'Safe simulated plant data for testing the app without hardware.',
    'source_separation': 'Simulation and ESP32 use separate histories. Switching never mixes their values.',
    'simulation_enabled': 'Simulation source enabled.',
    'latest_reading_no_health': 'New validated sensor reading received.',
    'live_sensors': 'Live Sensors',
    'farmer_analysis': 'Farmer Analysis',
    'farmer_subtitle': 'Simple guidance from the live plant condition.',
    'plant_condition': 'Plant Condition',
    'main_problem': 'Main Problem',
    'what_changed': 'What Changed',
    'what_to_do': 'What To Do',
    'analysis_confidence': 'Analysis Confidence',
    'advanced_details': 'Advanced Details',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'not_available': 'Unavailable',
    'simulation_active': 'Simulation active',
    'simulation_waiting': 'Preparing simulated plant data…',
    'why_happening': 'Why this is happening',
    'is_improving': 'Is it improving?',
    'no_problem': 'No major problem reported right now.',
    'no_change': 'No important recent change has been reported yet.',
    'keep_monitoring': 'Keep monitoring the plant.',
    'disconnected': 'ESP32 disconnected',
    'last_reading': 'Last reading',
    'live_subtitle': 'Real-time measurements and the ESP32 interpretation behind the plant result.',
    'air': 'Air',
    'light': 'Light',
    'soil_root': 'Soil & Root',
    'leaf': 'Leaf',
    'plant_signal': 'Plant Signal',
    'intelligence': 'Intelligence',
    'result': 'Result',
    'trend': 'Trend',
    'confidence': 'Confidence',
    'rate': 'Rate of change',
    'status': 'Status',
    'data_age': 'Data age',
    'effect': 'Effect on plant result',
    'technical': 'Technical',
    'raw': 'Raw reading',
    'unavailable': 'Sensor Unavailable',
    'no_interpretation': 'ESP32 interpretation not provided',
    'no_trend': 'Trend not provided',
    'no_confidence': 'Confidence not provided',
    'crop_profile': 'Crop Profile',
    'growth_stage': 'Growth Stage',
    'main_finding': 'Main finding',
    'secondary_finding': 'Secondary finding',
    'analysis_quality': 'Analysis quality',
    'disease_risk': 'Environmental Disease Risk',
    'disease_note': 'Environmental disease-conducive risk only — not a confirmed disease.',
    'air_temp': 'Air Temperature',
    'humidity': 'Relative Humidity',
    'light_lux': 'Light',
    'soil_moisture': 'Soil Moisture',
    'root_temp': 'Root / Soil Temperature',
    'leaf_wetness': 'Leaf Wetness',
    'bio_signal': 'Plant Bioelectric Signal',
    'bio_baseline': 'Bioelectric baseline',
    'bio_deviation': 'Bioelectric deviation',
    'air_root_delta': 'Air–Root Temperature Difference',
    'vpd': 'VPD / Air Drying Demand',
    'wet_duration': 'Leaf Wetness Duration',
    'day_phase': 'Day / Night phase',
    'health_score': 'Health score',
    'plant_state': 'Plant state',
    'baseline_note': 'Plant voltage is interpreted only relative to this plant’s learned baseline.',
    'vpd_note': 'This is a derived air-drying metric, not a direct sensor reading.',
    'recovering_title': 'PLANT IS RECOVERING',
    'recovery_summary': 'Conditions improved and the plant stress response is decreasing.',
    'recovery_action': 'No extra action is needed now. Continue monitoring.',
    'recovery_time': 'Recovering for',
    'recovering': 'Recovering',
    'severity': 'Severity',
    'do_this_now': 'Do this now',
    'making_it_worse': 'Making it worse',
    'why_button': 'Why?',
    'why_title': 'Why PhytoSense thinks this',
    'why_unavailable': 'The ESP32 has not provided enough evidence details yet.',
    'plant_response': 'Plant Response',
    'plant_response_no_result': 'Plant response is being monitored.',
    'plant_response_supported_by': 'Supported by',
    'persistent_for': 'Persistent for',
    'calm': 'Calm',
    'mild_response': 'Mild response',
    'stressed': 'Stressed',
    'strongly_stressed': 'Strongly stressed',
    'signal_unavailable': 'Signal unavailable',
    'learning_baseline': 'Learning this plant’s normal signal',
    'bio_learning_body': 'PhytoSense is learning the plant’s normal electrical pattern. Environmental monitoring continues.',
    'bio_signal_check_electrodes': 'The plant signal is not reliable right now. Check the electrode contact; environmental sensors are still being used.',
    'baseline_samples': 'Baseline samples',
    'baseline_progress': 'Baseline learning',
    'included_in_analysis': 'Included in ESP32 analysis',
    'excluded_from_analysis': 'Excluded from ESP32 analysis',
    'visual_inspection_recommended': 'Visual inspection recommended',
    'visual_inspection_body': 'The ESP32 recommends checking the plant with the camera and inspecting visible symptoms.',
    'possible_biotic_title': 'Possible pest or disease stress',
    'possible_biotic_body': 'The plant is showing an electrical stress response that is not fully explained by water, heat, humidity, root-zone temperature, or other environmental sensors.',
    'inspect_plant': 'Inspect Plant',
    'scan_plant_camera': 'Scan Plant With Camera',
    'recommended_action': 'Recommended action',
    'biotic_inspect_action': 'Inspect the leaves, stems, and undersides of leaves for pests or visible disease symptoms.',
    'biotic_why_title': 'Why PhytoSense suspects a biological cause',
    'biotic_evidence_bio': 'Bioelectric stress response is elevated.',
    'biotic_evidence_signal': 'The ESP32 reports confidence for this suspicion.',
    'biotic_evidence_environment': 'The usual environmental causes do not fully explain the response.',
    'biotic_inspection_reason': 'Because the usual environmental causes do not fully explain the plant response, PhytoSense recommends visual inspection.',
    'biotic_safety_note': 'This is a suspicion from sensor evidence, not a confirmed pest or disease diagnosis.',
    'biotic_analysis': 'Biotic Stress Analysis',
    'biotic_state': 'Biotic state',
    'biotic_evidence': 'Evidence',
    'biotic_confidence': 'Biotic confidence',
    'bio_stress_score': 'Bio stress score',
    'bio_signal_quality': 'Bio signal quality',
    'environmental_explanation': 'Environmental explanation',
    'primary_interpretation': 'Primary interpretation',
    'biotic_recommendation': 'Recommendation',
    'water_stress_evidence': 'Water-stress evidence',
    'heat_stress_evidence': 'Heat-stress evidence',
    'root_stress_evidence': 'Root-zone stress evidence',
    'air_drying_evidence': 'Air-drying evidence',
    'camera_sensor_combined': 'Camera + sensor inspection',
    'camera_possible_match': 'Possible visual match',
    'camera_combined_body': 'PhytoSense reported unexplained plant stress, and the camera found visible features consistent with this possibility.',
    'camera_confirm_before_treatment': 'Inspect the plant closely and confirm the visible signs before treatment.',
    'camera_no_clear_title': 'Plant stress needs inspection',
    'camera_no_clear_body': 'No clear visible pest or disease was identified by the camera. Continue monitoring and inspect the plant manually.',
    'camera_result_separation': 'The camera adds visual evidence; it does not change the ESP32 bioelectric result.',
    'camera_inspection_started': 'Camera inspection started',
    'camera_inspection_completed': 'Camera inspection completed',
    'camera_no_clear_event': 'No clear visible pest or disease identified',
    'sensor_attention': 'A sensor needs attention',
    'degraded_body': 'PhytoSense is continuing with the remaining reliable sensors.',
    'esp32_connected': 'ESP32 Live connected',
    'waiting_esp32': 'Waiting for a validated ESP32 reading…',
    'improving': 'Improving',
    'stable': 'Stable',
    'getting_worse': 'Getting worse',
    'getting_worse_quickly': 'Getting worse quickly',
    'air_drying': 'Air drying demand',
    'plant_electrical_response': 'Plant Electrical Response',
    'stress_score': 'Stress score',
    'evidence_separation_title': 'Sensor and visual evidence stay separate',
    'sensor_inspection_prompt': 'Sensor evidence suggested a closer inspection. The camera result below will use only the photo and your visible-symptom answers.',
    'camera_visual_only': 'Camera screening uses visible evidence only. It does not silently combine ESP32 sensor readings into the visual result.',
    'visual_evidence': 'Visual evidence',
    'visual_evidence_body': 'Photo colour patterns and visible symptom answers are used for the camera screening result.',
    'sensor_evidence': 'Sensor evidence',
    'sensor_evidence_body': 'ESP32 stress, root-cause and environmental evidence remain a separate analysis in Home and Analysis.',
    'observed_sequence_note': 'Observed event sequence — useful for timing, not proof of causation.',
    'recent_trend': 'Recent trend',
    'health_history': 'Plant condition history',
    'soil_history': 'Root soil history',
    'stress_history': 'Plant response history',
    'no_history': 'Not enough history yet. Keep PhytoSense running to build a trend.',
    'sensor_event': 'Sensor event',
    'plant_event': 'Plant event',
    'alert_event': 'Alert',
    'sensor_reliability': 'Sensor Reliability',
    'sensor_health': 'Sensor Health',
    'some_sensors_attention': 'Some sensors need attention',
    'all_sensors_good': 'Sensors are reliable',
    'environmental_risk': 'Environmental Risk',
    'atmospheric_drying': 'Atmospheric Drying',
    'root_zone_water': 'Root-Zone Water',
    'water_balance': 'Water Balance',
    'full_analysis': 'View Full Analysis',
    'technical_judge_view': 'Technical / Judge View',
    'possible_causes': 'Possible Causes',
    'bioelectric_response': 'Bioelectric Response',
    'baseline_stable': 'Baseline Stable',
    'signal_quality': 'Signal Quality',
    'reduced_confidence': 'Analysis continuing with reduced sensor confidence',
    'analysis_quality_high': 'PhytoSense has strong sensor evidence.',
    'analysis_quality_moderate': 'Some sensor information is unavailable.',
    'analysis_quality_low': 'Check sensor connections before relying on this analysis.',
    'humidity_unavailable': 'Humidity sensor data is temporarily unavailable.',
    'environment_monitoring_continues': 'Environmental monitoring is continuing.',
    'speak_summary': 'Speak farmer summary',
    'firmware_compatibility_title': 'Firmware compatibility issue',
    'firmware_compatibility_body': 'This ESP32 payload uses a newer unsupported schema. Update PhytoSense AI before trusting the analysis.',
  };

  static const _taLabels = <String, String>{
    'analysis': 'பகுப்பாய்வு',
    'sensors': 'சென்சார்கள்',
    'history': 'வரலாறு',
    'camera': 'கேமரா',
    'settings': 'அமைப்புகள்',
    'simulation': 'Simulation',
    'simulated': 'SIMULATED',
    'simulation_description': 'Hardware இல்லாமல் app-ஐ சோதிக்க பாதுகாப்பான simulation செடி தரவு.',
    'source_separation': 'Simulation மற்றும் ESP32 தனித்தனி history பயன்படுத்தும். மாற்றும்போது values கலக்காது.',
    'simulation_enabled': 'Simulation source இயக்கப்பட்டது.',
    'latest_reading_no_health': 'புதிய validated sensor reading கிடைத்தது.',
    'live_sensors': 'Live Sensors',
    'farmer_analysis': 'விவசாயி பகுப்பாய்வு',
    'farmer_subtitle': 'நேரடி செடி நிலையை எளிய வழிகாட்டலாக காட்டுகிறது.',
    'plant_condition': 'செடியின் நிலை',
    'main_problem': 'முக்கிய பிரச்சினை',
    'what_changed': 'என்ன மாற்றம் ஏற்பட்டது?',
    'what_to_do': 'என்ன செய்ய வேண்டும்?',
    'analysis_confidence': 'பகுப்பாய்வு நம்பிக்கை',
    'advanced_details': 'மேம்பட்ட விவரங்கள்',
    'high': 'உயர்',
    'medium': 'நடுத்தரம்',
    'low': 'குறைவு',
    'not_available': 'தகவல் கிடைக்கவில்லை',
    'simulation_active': 'Simulation செயலில் உள்ளது',
    'simulation_waiting': 'Simulation செடி தகவல் தயாராகிறது…',
    'why_happening': 'இது ஏன் நடக்கிறது?',
    'is_improving': 'நிலை மேம்படுகிறதா?',
    'no_problem': 'இப்போது பெரிய பிரச்சினை எதுவும் தெரிவிக்கப்படவில்லை.',
    'no_change': 'முக்கியமான சமீப மாற்றம் இன்னும் தெரிவிக்கப்படவில்லை.',
    'keep_monitoring': 'செடியை தொடர்ந்து கண்காணிக்கவும்.',
    'disconnected': 'ESP32 இணைப்பு துண்டிக்கப்பட்டது',
    'last_reading': 'கடைசி reading',
    'live_subtitle': 'நேரடி அளவீடுகள் மற்றும் plant result-க்கு பின்னுள்ள ESP32 விளக்கம்.',
    'air': 'காற்று',
    'light': 'ஒளி',
    'soil_root': 'மண் & வேர்',
    'leaf': 'இலை',
    'plant_signal': 'செடி மின்சார சிக்னல்',
    'intelligence': 'பகுப்பாய்வு',
    'result': 'முடிவு',
    'trend': 'போக்கு',
    'confidence': 'நம்பிக்கை',
    'rate': 'மாற்ற வேகம்',
    'status': 'நிலை',
    'data_age': 'தரவு வயது',
    'effect': 'செடி முடிவில் தாக்கம்',
    'technical': 'தொழில்நுட்பம்',
    'raw': 'Raw reading',
    'unavailable': 'சென்சார் கிடைக்கவில்லை',
    'no_interpretation': 'ESP32 விளக்கம் வழங்கவில்லை',
    'no_trend': 'போக்கு தகவல் இல்லை',
    'no_confidence': 'நம்பிக்கை தகவல் இல்லை',
    'crop_profile': 'பயிர் Profile',
    'growth_stage': 'வளர்ச்சி நிலை',
    'main_finding': 'முக்கிய கண்டுபிடிப்பு',
    'secondary_finding': 'இரண்டாம் கண்டுபிடிப்பு',
    'analysis_quality': 'பகுப்பாய்வு தரம்',
    'disease_risk': 'சுற்றுச்சூழல் நோய் அபாயம்',
    'disease_note': 'இது நோய்க்கு சாதகமான சூழல் அபாயம் மட்டும்; உறுதியான நோய் கண்டறிதல் அல்ல.',
    'air_temp': 'காற்று வெப்பநிலை',
    'humidity': 'ஈரப்பதம்',
    'light_lux': 'ஒளி',
    'soil_moisture': 'மண் ஈரப்பதம்',
    'root_temp': 'வேர் / மண் வெப்பநிலை',
    'leaf_wetness': 'இலை ஈரப்பதம்',
    'bio_signal': 'செடி மின்சார சிக்னல்',
    'bio_baseline': 'Bioelectric baseline',
    'bio_deviation': 'Bioelectric deviation',
    'air_root_delta': 'காற்று–வேர் வெப்பநிலை வேறுபாடு',
    'vpd': 'VPD / காற்றின் உலர்த்தும் தாக்கம்',
    'wet_duration': 'இலை ஈரமாக இருந்த நேரம்',
    'day_phase': 'பகல் / இரவு நிலை',
    'health_score': 'Health score',
    'plant_state': 'செடி நிலை',
    'baseline_note': 'செடி voltage இந்த செடியின் கற்ற baseline-ஐ ஒப்பிட்டு மட்டுமே விளக்கப்படுகிறது.',
    'vpd_note': 'இது நேரடி sensor reading அல்ல; கணக்கிடப்பட்ட air-drying metric.',
    'recovering_title': 'செடி மீண்டு வருகிறது',
    'recovery_summary': 'சூழல் மேம்பட்டுள்ளது; செடியின் அழுத்தச் சிக்னல் குறைந்து வருகிறது.',
    'recovery_action': 'இப்போது கூடுதல் நடவடிக்கை தேவையில்லை. தொடர்ந்து கண்காணிக்கவும்.',
    'recovery_time': 'மீண்டு வரும் நேரம்',
    'recovering': 'மீண்டு வருகிறது',
    'severity': 'தீவிரம்',
    'do_this_now': 'இப்போது செய்ய வேண்டியது',
    'making_it_worse': 'மேலும் பாதிக்கிறது',
    'why_button': 'ஏன்?',
    'why_title': 'PhytoSense இந்த முடிவை ஏன் சொல்கிறது',
    'why_unavailable': 'ESP32 இன்னும் போதுமான காரண விவரங்களை வழங்கவில்லை.',
    'plant_response': 'செடியின் பதில்',
    'plant_response_no_result': 'செடியின் பதில் தொடர்ந்து கண்காணிக்கப்படுகிறது.',
    'plant_response_supported_by': 'ஆதரிக்கும் தகவல்கள்',
    'persistent_for': 'தொடர்ந்து உள்ளது',
    'calm': 'அமைதியான பதில்',
    'mild_response': 'லேசான பதில்',
    'stressed': 'அழுத்தத்தில் உள்ளது',
    'strongly_stressed': 'அதிக அழுத்தத்தில் உள்ளது',
    'signal_unavailable': 'சிக்னல் கிடைக்கவில்லை',
    'learning_baseline': 'இந்தச் செடியின் இயல்பான சிக்னல் கற்றுக்கொள்ளப்படுகிறது',
    'bio_learning_body': 'செடியின் இயல்பான மின்சார முறையை PhytoSense கற்றுக்கொள்கிறது. சுற்றுச்சூழல் கண்காணிப்பு தொடர்கிறது.',
    'bio_signal_check_electrodes': 'இப்போது செடியின் சிக்னல் நம்பகமாக இல்லை. மின்முனை இணைப்பைச் சரிபார்க்கவும்; சுற்றுச்சூழல் சென்சார்கள் தொடர்ந்து பயன்படுத்தப்படுகின்றன.',
    'baseline_samples': 'அடிப்படை மாதிரிகள்',
    'baseline_progress': 'அடிப்படை கற்றல்',
    'included_in_analysis': 'ESP32 பகுப்பாய்வில் சேர்க்கப்பட்டுள்ளது',
    'excluded_from_analysis': 'ESP32 பகுப்பாய்வில் இருந்து விலக்கப்பட்டுள்ளது',
    'visual_inspection_recommended': 'கேமரா ஆய்வு பரிந்துரைக்கப்படுகிறது',
    'visual_inspection_body': 'கேமராவால் செடியைப் பார்த்து, தெரியும் அறிகுறிகளை ஆய்வு செய்ய ESP32 பரிந்துரைக்கிறது.',
    'possible_biotic_title': 'பூச்சி அல்லது நோய் அழுத்தம் இருக்கலாம்',
    'possible_biotic_body': 'செடியின் மின்சாரப் பதிலில் அழுத்தம் தெரிகிறது. நீர், வெப்பம், ஈரப்பதம், வேர் பகுதி வெப்பநிலை மற்றும் பிற சுற்றுச்சூழல் சென்சார்கள் இதை முழுமையாக விளக்கவில்லை.',
    'inspect_plant': 'செடியை பாருங்கள்',
    'scan_plant_camera': 'கேமராவில் செடியை ஆய்வு செய்க',
    'recommended_action': 'பரிந்துரைக்கப்படும் நடவடிக்கை',
    'biotic_inspect_action': 'இலைகள், தண்டுகள் மற்றும் இலைகளின் அடிப்புறத்தில் பூச்சி அல்லது நோய் அறிகுறிகள் உள்ளதா பாருங்கள்.',
    'biotic_why_title': 'உயிரியல் காரணம் இருக்கலாம் என்று PhytoSense ஏன் கருதுகிறது?',
    'biotic_evidence_bio': 'செடியின் Bioelectric அழுத்தப் பதில் அதிகரித்துள்ளது.',
    'biotic_evidence_signal': 'இந்த சந்தேகத்திற்கான நம்பிக்கை அளவை ESP32 வழங்கியுள்ளது.',
    'biotic_evidence_environment': 'வழக்கமான சுற்றுச்சூழல் காரணங்கள் இந்தப் பதிலை முழுமையாக விளக்கவில்லை.',
    'biotic_inspection_reason': 'வழக்கமான சுற்றுச்சூழல் காரணங்கள் செடியின் பதிலை முழுமையாக விளக்காததால், செடியை நேரில் ஆய்வு செய்ய PhytoSense பரிந்துரைக்கிறது.',
    'biotic_safety_note': 'இது சென்சார் ஆதாரத்தின் அடிப்படையிலான சந்தேகம் மட்டும்; பூச்சி அல்லது நோய் உறுதி அல்ல.',
    'biotic_analysis': 'உயிரியல் அழுத்தப் பகுப்பாய்வு',
    'biotic_state': 'உயிரியல் அழுத்த நிலை',
    'biotic_evidence': 'ஆதாரம்',
    'biotic_confidence': 'உயிரியல் பகுப்பாய்வு நம்பிக்கை',
    'bio_stress_score': 'Bio அழுத்த மதிப்பெண்',
    'bio_signal_quality': 'Bio சிக்னல் தரம்',
    'environmental_explanation': 'சுற்றுச்சூழல் காரண விளக்கம்',
    'primary_interpretation': 'முக்கிய விளக்கம்',
    'biotic_recommendation': 'பரிந்துரை',
    'water_stress_evidence': 'நீர் பற்றாக்குறை அழுத்த ஆதாரம்',
    'heat_stress_evidence': 'வெப்ப அழுத்த ஆதாரம்',
    'root_stress_evidence': 'வேர் பகுதி அழுத்த ஆதாரம்',
    'air_drying_evidence': 'காற்று உலர்த்தும் தாக்க ஆதாரம்',
    'camera_sensor_combined': 'கேமரா + சென்சார் ஆய்வு',
    'camera_possible_match': 'காட்சியில் இருக்கக்கூடிய பொருத்தம்',
    'camera_combined_body': 'காரணம் தெளிவில்லாத செடி அழுத்தத்தை PhytoSense தெரிவித்தது; கேமராவில் இந்த சாத்தியத்துடன் பொருந்தும் காட்சி அறிகுறிகள் தெரிகின்றன.',
    'camera_confirm_before_treatment': 'சிகிச்சைக்கு முன் செடியை நன்றாகப் பார்த்து அறிகுறிகளை உறுதி செய்யவும்.',
    'camera_no_clear_title': 'செடியை நேரில் ஆய்வு செய்ய வேண்டும்',
    'camera_no_clear_body': 'கேமராவில் தெளிவான பூச்சி அல்லது நோய் தெரியவில்லை. தொடர்ந்து கண்காணித்து செடியை நேரில் பாருங்கள்.',
    'camera_result_separation': 'கேமரா காட்சி ஆதாரத்தை மட்டும் சேர்க்கிறது; ESP32 Bioelectric முடிவை மாற்றாது.',
    'camera_inspection_started': 'கேமரா ஆய்வு தொடங்கியது',
    'camera_inspection_completed': 'கேமரா ஆய்வு முடிந்தது',
    'camera_no_clear_event': 'தெளிவான பூச்சி அல்லது நோய் தெரியவில்லை',
    'sensor_attention': 'ஒரு சென்சாரை சரிபார்க்க வேண்டும்',
    'degraded_body': 'நம்பகமான மற்ற சென்சார்களுடன் PhytoSense பகுப்பாய்வைத் தொடர்ந்து செய்கிறது.',
    'esp32_connected': 'ESP32 நேரடி இணைப்பு உள்ளது',
    'waiting_esp32': 'சரிபார்க்கப்பட்ட ESP32 தகவலுக்காக காத்திருக்கிறது…',
    'improving': 'மேம்படுகிறது',
    'stable': 'நிலையாக உள்ளது',
    'getting_worse': 'மோசமாகிறது',
    'getting_worse_quickly': 'வேகமாக மோசமாகிறது',
    'air_drying': 'காற்றின் உலர்த்தும் தாக்கம்',
    'plant_electrical_response': 'செடியின் மின்சார பதில்',
    'stress_score': 'அழுத்த மதிப்பெண்',
    'evidence_separation_title': 'சென்சார் மற்றும் காட்சி ஆதாரம் தனித்தனியாக இருக்கும்',
    'sensor_inspection_prompt': 'சென்சார் தகவல் செடியை நேரில் பார்க்கச் சொல்கிறது. கேமரா முடிவு புகைப்படம் மற்றும் நீங்கள் காணும் அறிகுறிகளை மட்டும் பயன்படுத்தும்.',
    'camera_visual_only': 'கேமரா ஆய்வு காட்சி ஆதாரத்தை மட்டும் பயன்படுத்தும். ESP32 சென்சார் முடிவுகள் இதில் மறைமுகமாக கலக்கப்படாது.',
    'visual_evidence': 'காட்சி ஆதாரம்',
    'visual_evidence_body': 'புகைப்பட நிற அமைப்பு மற்றும் தெளிவாக காணும் அறிகுறிகள் கேமரா ஆய்வில் பயன்படுத்தப்படும்.',
    'sensor_evidence': 'சென்சார் ஆதாரம்',
    'sensor_evidence_body': 'ESP32 stress, root-cause மற்றும் சுற்றுச்சூழல் தகவல்கள் Home மற்றும் Analysis-ல் தனி பகுப்பாய்வாக இருக்கும்.',
    'observed_sequence_note': 'இது காணப்பட்ட நிகழ்வு வரிசை மட்டும்; காரணத்தை நிரூபிப்பதல்ல.',
    'recent_trend': 'சமீப போக்கு',
    'health_history': 'செடி நிலை வரலாறு',
    'soil_history': 'வேர் மண் வரலாறு',
    'stress_history': 'செடி பதில் வரலாறு',
    'no_history': 'போதுமான வரலாறு இன்னும் இல்லை. போக்கை உருவாக்க PhytoSense-ஐ தொடர்ந்து இயக்கவும்.',
    'sensor_event': 'சென்சார் நிகழ்வு',
    'plant_event': 'செடி நிகழ்வு',
    'alert_event': 'எச்சரிக்கை',
    'sensor_reliability': 'சென்சார் நம்பகத்தன்மை',
    'sensor_health': 'சென்சார் நிலை',
    'some_sensors_attention': 'சில சென்சார்களை சரிபார்க்க வேண்டும்',
    'all_sensors_good': 'சென்சார்கள் நம்பகமாக உள்ளன',
    'environmental_risk': 'சுற்றுச்சூழல் அபாயம்',
    'atmospheric_drying': 'காற்றின் உலர்த்தும் தாக்கம்',
    'root_zone_water': 'வேர் பகுதி நீர் நிலை',
    'water_balance': 'நீர் சமநிலை',
    'full_analysis': 'முழு பகுப்பாய்வைக் காண்க',
    'technical_judge_view': 'Technical / Judge View',
    'possible_causes': 'சாத்தியமான காரணங்கள்',
    'bioelectric_response': 'Bioelectric பதில்',
    'baseline_stable': 'Baseline நிலையாக உள்ளது',
    'signal_quality': 'சிக்னல் தரம்',
    'reduced_confidence': 'குறைந்த சென்சார் நம்பகத்தன்மையுடன் பகுப்பாய்வு தொடர்கிறது',
    'analysis_quality_high': 'PhytoSense-க்கு வலுவான சென்சார் ஆதாரம் உள்ளது.',
    'analysis_quality_moderate': 'சில சென்சார் தகவல்கள் கிடைக்கவில்லை.',
    'analysis_quality_low': 'இந்த பகுப்பாய்வை நம்புவதற்கு முன் சென்சார் இணைப்புகளைச் சரிபார்க்கவும்.',
    'humidity_unavailable': 'ஈரப்பதம் சென்சார் தகவல் தற்காலிகமாக கிடைக்கவில்லை.',
    'environment_monitoring_continues': 'சுற்றுச்சூழல் கண்காணிப்பு தொடர்ந்து நடைபெறுகிறது.',
    'speak_summary': 'விவசாயி சுருக்கத்தை கேட்கவும்',
    'firmware_compatibility_title': 'Firmware பொருந்தவில்லை',
    'firmware_compatibility_body': 'இந்த ESP32 payload ஆதரிக்கப்படாத புதிய schema-ஐ பயன்படுத்துகிறது. பகுப்பாய்வை நம்புவதற்கு முன் PhytoSense AI-ஐ புதுப்பிக்கவும்.',
  };

  static const _enFirmware = <String, String>{
    'HEALTHY': 'Healthy', 'EXCELLENT': 'Excellent', 'GOOD': 'Good', 'ACCEPTABLE': 'Acceptable',
    'NEEDS_ATTENTION': 'Needs Attention', 'WATCH': 'Needs Attention', 'STRESSED': 'Stressed',
    'HIGH_STRESS': 'High Stress', 'CRITICAL': 'Critical', 'RECOVERING': 'Recovering',
    'LOW': 'Low', 'HIGH': 'High', 'DRY': 'Dry', 'VERY_DRY': 'Very Dry', 'WET': 'Wet',
    'TOO_WET': 'Too Wet', 'VERY_WET': 'Very Wet', 'COOL': 'Cool', 'WARM': 'Warm',
    'WARM_NIGHT': 'Warm Night', 'HOT': 'Too Hot', 'HEAT_STRESS': 'Heat Stress',
    'EXTREME_HEAT': 'Extreme Heat', 'OPTIMAL': 'Good', 'STABLE': 'Stable', 'RISING': 'Rising',
    'RISING_FAST': 'Rising Quickly', 'RISING_QUICKLY': 'Rising Quickly', 'FALLING': 'Falling',
    'FALLING_FAST': 'Falling Quickly', 'FALLING_QUICKLY': 'Falling Quickly',
    'MISSING': 'Sensor Unavailable', 'UNAVAILABLE': 'Sensor Unavailable',
    'INVALID': 'Reading Unreliable', 'STALE': 'Reading Delayed',
    'LEARNING_BASELINE': 'Learning this plant’s normal electrical pattern',
    'BASELINE_STABLE': 'Stable relative to learned baseline',
    'STRESS_CORROBORATED': 'Electrical change supports stress seen by other sensors',
    'STRONG_EP_CHANGE': 'Strong change from learned baseline', 'EP_CHANGE': 'Changed from learned baseline',
    'KEEP_MONITORING': 'Keep monitoring the plant.', 'WATER_SOON': 'Water the root zone soon.',
    'WATER_ROOT_ZONE_NOW': 'Water the root zone now.',
    'DRY_LEAVES_VENTILATE': 'Dry the leaves and improve airflow.',
    'KEEP_LEAVES_DRY': 'Keep the leaves dry and improve airflow.',
    'CHECK_DRAINAGE_PAUSE_WATER': 'Check drainage and pause watering.',
    'COOL_ROOT_ZONE': 'Reduce heat around the root zone.',
    'PROTECT_ROOT_ZONE': 'Protect the root zone from temperature extremes.',
    'INSPECT_PLANT_TODAY': 'Inspect the plant today.',
    'CALIBRATE_LEAF_SENSOR': 'Calibrate the leaf-wetness sensor.',
    'CHECK_SENSOR_WIRING': 'Check the sensor connection.',
    'NO_URGENT_STRESS_DETECTED': 'No urgent stress detected',
    'ROOT_ZONE_IS_DRY': 'Root soil is too dry',
    'HIGH_DISEASE_CONDUCIVE_CONDITIONS': 'Conditions are highly favourable for disease development',
    'LEAF_WETNESS_RISK_IS_RISING': 'Leaf-wetness related environmental risk is rising',
    'SOIL_INDEX_STAYED_VERY_WET': 'Soil has stayed very wet',
    'WATER_STRESS': 'Water stress',
    'ROOT_ZONE_STRESS': 'Root-zone stress',
    'HIGH_ATMOSPHERIC_DRYING_DEMAND': 'The air is pulling water from the plant quickly',
    'UNEXPLAINED_PLANT_STRESS': 'Unexplained plant stress',
    'POSSIBLE_BIOTIC_STRESS': 'Possible pest or disease stress',
    'INSUFFICIENT_DATA': 'Not enough data yet',
    'LOW_CONFIDENCE': 'Reduced-confidence analysis',
    'NONE': 'No biotic stress reported',
    'STRESS_SIGNAL': 'The plant is showing a stress response',
    'MILD_RESPONSE': 'Mild response',
    'STRONG_STRESS': 'Strong stress response',
    'CALM': 'Calm',
    'SUSPECTED': 'Possible biotic stress',
    'SIGNAL_NOISY': 'Signal noisy', 'CHECK_CONTACT': 'Check electrode contact',
    'AMP_HIGH_RAIL': 'Amplifier high rail', 'AMP_LOW_RAIL': 'Amplifier low rail',
    'SATURATED': 'Signal saturated', 'STRONG_STRESS_SIGNAL': 'Strong stress signal',
  };

  static const _taFirmware = <String, String>{
    'HEALTHY': 'ஆரோக்கியமான நிலை', 'EXCELLENT': 'மிக நல்ல நிலை', 'GOOD': 'நல்ல நிலை',
    'ACCEPTABLE': 'ஏற்ற நிலை', 'NEEDS_ATTENTION': 'கவனம் தேவை', 'WATCH': 'கவனம் தேவை',
    'STRESSED': 'Stress உள்ளது', 'HIGH_STRESS': 'அதிக stress', 'CRITICAL': 'அவசர நிலை',
    'RECOVERING': 'மீண்டு வருகிறது', 'LOW': 'குறைவு', 'HIGH': 'அதிகம்', 'DRY': 'உலர்',
    'VERY_DRY': 'மிகவும் உலர்', 'WET': 'ஈரமாக உள்ளது', 'TOO_WET': 'அதிக ஈரம்',
    'VERY_WET': 'மிக அதிக ஈரம்', 'COOL': 'குளிர்ச்சி', 'WARM': 'சூடாக உள்ளது',
    'WARM_NIGHT': 'சூடான இரவு', 'HOT': 'அதிக வெப்பம்', 'HEAT_STRESS': 'வெப்ப stress',
    'EXTREME_HEAT': 'மிக அதிக வெப்பம்', 'OPTIMAL': 'நல்ல நிலை', 'STABLE': 'நிலையாக உள்ளது',
    'RISING': 'அதிகரிக்கிறது', 'RISING_FAST': 'வேகமாக அதிகரிக்கிறது',
    'RISING_QUICKLY': 'வேகமாக அதிகரிக்கிறது', 'FALLING': 'குறைகிறது',
    'FALLING_FAST': 'வேகமாக குறைகிறது', 'FALLING_QUICKLY': 'வேகமாக குறைகிறது',
    'MISSING': 'சென்சார் கிடைக்கவில்லை', 'UNAVAILABLE': 'சென்சார் கிடைக்கவில்லை',
    'INVALID': 'Reading நம்பகமில்லை', 'STALE': 'Reading தாமதமாக உள்ளது',
    'LEARNING_BASELINE': 'இந்த செடியின் இயல்பான மின்சார pattern கற்றுக்கொள்ளப்படுகிறது',
    'BASELINE_STABLE': 'கற்ற baseline-ஐ ஒப்பிடும்போது நிலையாக உள்ளது',
    'STRESS_CORROBORATED': 'மற்ற சென்சார்கள் காட்டும் stress-ஐ மின்சார மாற்றமும் ஆதரிக்கிறது',
    'STRONG_EP_CHANGE': 'கற்ற baseline-இலிருந்து பெரிய மாற்றம்', 'EP_CHANGE': 'கற்ற baseline-இலிருந்து மாற்றம்',
    'KEEP_MONITORING': 'செடியை தொடர்ந்து கண்காணிக்கவும்.',
    'WATER_SOON': 'வேர் பகுதியை விரைவில் நீர்ப்பாய்ச்சவும்.',
    'WATER_ROOT_ZONE_NOW': 'வேர் பகுதியை இப்போது நீர்ப்பாய்ச்சவும்.',
    'DRY_LEAVES_VENTILATE': 'இலைகளை உலர வைத்து காற்றோட்டத்தை மேம்படுத்தவும்.',
    'KEEP_LEAVES_DRY': 'இலைகளை உலர வைத்துக் காற்றோட்டத்தை மேம்படுத்தவும்.',
    'CHECK_DRAINAGE_PAUSE_WATER': 'Drainage-ஐ சரிபார்த்து நீர்ப்பாய்ச்சலை தற்காலிகமாக நிறுத்தவும்.',
    'COOL_ROOT_ZONE': 'வேர் பகுதியின் வெப்பத்தை குறைக்கவும்.',
    'PROTECT_ROOT_ZONE': 'வேர் பகுதியை அதிக வெப்பம்/குளிரிலிருந்து பாதுகாக்கவும்.',
    'INSPECT_PLANT_TODAY': 'இன்று செடியை நேரில் பாருங்கள்.',
    'CALIBRATE_LEAF_SENSOR': 'Leaf-wetness sensor-ஐ calibrate செய்யவும்.',
    'CHECK_SENSOR_WIRING': 'சென்சார் இணைப்பைச் சரிபார்க்கவும்.',
    'NO_URGENT_STRESS_DETECTED': 'அவசரமான stress இல்லை',
    'ROOT_ZONE_IS_DRY': 'வேர் பகுதியிலுள்ள மண் மிகவும் உலர்ந்துள்ளது',
    'HIGH_DISEASE_CONDUCIVE_CONDITIONS': 'நோய் வளர்ச்சிக்கு மிகவும் சாதகமான சூழல் உள்ளது',
    'LEAF_WETNESS_RISK_IS_RISING': 'இலை ஈரத்துடன் தொடர்புடைய சுற்றுச்சூழல் அபாயம் அதிகரிக்கிறது',
    'SOIL_INDEX_STAYED_VERY_WET': 'மண் நீண்ட நேரமாக மிகவும் ஈரமாக உள்ளது',
    'WATER_STRESS': 'நீர் பற்றாக்குறை அழுத்தம்',
    'ROOT_ZONE_STRESS': 'வேர் பகுதி அழுத்தம்',
    'HIGH_ATMOSPHERIC_DRYING_DEMAND': 'காற்று செடியிலிருந்து நீரை வேகமாக இழுக்கிறது',
    'UNEXPLAINED_PLANT_STRESS': 'காரணம் தெளிவில்லாத செடி அழுத்தம்',
    'POSSIBLE_BIOTIC_STRESS': 'பூச்சி அல்லது நோய் அழுத்தம் இருக்கலாம்',
    'INSUFFICIENT_DATA': 'போதுமான தரவு இன்னும் இல்லை',
    'LOW_CONFIDENCE': 'குறைந்த நம்பிக்கையுள்ள பகுப்பாய்வு',
    'NONE': 'உயிரியல் அழுத்தம் தெரிவிக்கப்படவில்லை',
    'STRESS_SIGNAL': 'செடி அழுத்தப் பதிலை காட்டுகிறது',
    'MILD_RESPONSE': 'லேசான பதில்',
    'STRONG_STRESS': 'அதிக அழுத்தப் பதில்',
    'CALM': 'அமைதியான நிலை',
    'SUSPECTED': 'உயிரியல் காரண அழுத்தம் இருக்கலாம்',
    'SIGNAL_NOISY': 'சிக்னலில் அதிக சத்தம் உள்ளது', 'CHECK_CONTACT': 'Electrode இணைப்பைச் சரிபார்க்கவும்',
    'AMP_HIGH_RAIL': 'Amplifier high rail', 'AMP_LOW_RAIL': 'Amplifier low rail',
    'SATURATED': 'சிக்னல் saturated', 'STRONG_STRESS_SIGNAL': 'வலுவான stress signal',
  };
}
